services:
  socket-io-server:
    build:
      context: ../..
      dockerfile: devops/socket.io/Dockerfile
    image: socket-io-server:latest
    container_name: socket-io-server
    ports:
      - "3001:3001"
    env_file:
      # ‚Üê optional, .env is auto-loaded anyway
      - .env
    restart: unless-stopped
